/**
 * Compiles apps/mobile/assets/legal/*.md into a TypeScript module so the
 * documents render identically on web, iOS and Android without file IO.
 * Run: npm run legal  (CI verifies the generated file is up to date).
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const root = resolve(__dirname, '..');
const dir = join(root, 'apps/mobile/assets/legal');
const out = join(root, 'apps/mobile/src/legal/content.ts');

export function buildLegalModule(): string {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort();
  const entries = files.map((f) => {
    const [doc, lang] = f.replace('.md', '').split('.');
    return `  '${doc}.${lang}': ${JSON.stringify(readFileSync(join(dir, f), 'utf8'))},`;
  });
  return `// Generated by scripts/build-legal.ts from apps/mobile/assets/legal/*.md — do not edit.\nexport const LEGAL_DOCS: Record<string, string> = {\n${entries.join('\n')}\n};\n`;
}

if (require.main === module) {
  writeFileSync(out, buildLegalModule());
  console.log(`✓ ${out.replace(`${root}/`, '')}`);
}
