/**
 * Generates supabase/seed.sql from the same deterministic demo world the app
 * uses in demo mode: 50 traders, follow graph, ~500 trades, 80 theses,
 * posts, comments, likes, badges, precomputed leaderboards, app config and
 * region rules. Run: npm run seed:sql
 */
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import {
  BADGES,
  CATALOG,
  createMockProviders,
  DEFAULT_FEES,
  DEFAULT_MIN_ORDER_USD,
  DEFAULT_TIER_THRESHOLDS,
  DemoBackend,
  PERP_BASES,
  REGION_RULES,
  rankBy,
  seasonFor,
  thesisAccuracyPct,
  traderMetrics,
  qualifies,
} from '../packages/core/src';

const SEED = 20260924;

/** The auth trigger already created an empty profile row; overwrite every seeded column. */
const PROFILE_UPSERT = [
  'username',
  'display_name',
  'bio',
  'country_code',
  'birth_year',
  'interests',
  'holdings_public',
  'share_exact_amounts',
  'tier',
  'kyc_status',
  'language',
  'onboarded_at',
  'risk_accepted_at',
  'created_at',
]
  .map((c) => `${c} = excluded.${c}`)
  .join(', ');

/** Deterministic UUID v4-shaped id for a demo record id. */
function uuid(id: string): string {
  const h = createHash('sha1').update(`hopium:${id}`).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`;
}
const q = (v: string | null | undefined): string =>
  v === null || v === undefined ? 'null' : `'${v.replace(/'/g, "''")}'`;
const arr = (v: string[]): string => `'{${v.map((x) => `"${x}"`).join(',')}}'`;
const json = (v: unknown): string =>
  v === null || v === undefined ? 'null' : `${q(JSON.stringify(v))}::jsonb`;

export function buildSeedSql(): string {
  const providers = createMockProviders({ latency: [0, 0], failureRate: 0, seed: SEED });
  const demo = new DemoBackend(providers, { seed: SEED, engines: false });
  const db = demo.inspect();
  const out: string[] = ['-- Generated by scripts/seed-demo.ts — do not edit by hand.', 'begin;'];

  // Catalog
  for (const c of CATALOG) {
    out.push(
      `insert into public.assets (id, symbol, name, class, chain, decimals, tags) values (${q(c.id)}, ${q(c.symbol)}, ${q(c.name)}, ${q(c.class)}, ${q(c.chain)}, ${c.decimals}, ${arr(c.tags)}) on conflict (id) do nothing;`,
    );
  }
  for (const base of PERP_BASES) {
    out.push(
      `insert into public.assets (id, symbol, name, class, decimals, tags) values (${q(`${base.toLowerCase()}-perp`)}, ${q(`${base}-PERP`)}, ${q(`${base} Perpetual`)}, 'perp', 18, '{perp}') on conflict (id) do nothing;`,
    );
  }
  // Config, region rules, badges
  const season = seasonFor(Date.now());
  for (const [key, value] of Object.entries({
    fees: DEFAULT_FEES,
    min_order_usd: DEFAULT_MIN_ORDER_USD,
    max_slippage_bps: 2000,
    tier_thresholds: DEFAULT_TIER_THRESHOLDS,
    idr_per_usd: '16250',
    season,
    feature_flags: { copy_trade: true, stock_tokens: true, perps: true },
  }))
    out.push(
      `insert into public.app_config (key, value) values (${q(key)}, ${json(value)}) on conflict (key) do update set value = excluded.value;`,
    );
  for (const r of REGION_RULES) {
    out.push(
      `insert into public.region_rules (country_code, allow_stock_tokens, allow_perps, allow_copy_trade, requires_kyc_for) values (${q(r.countryCode)}, ${r.allowStockTokens}, ${r.allowPerps}, ${r.allowCopyTrade}, ${arr(r.requiresKycFor)}) on conflict (country_code) do nothing;`,
    );
  }
  for (const b of BADGES) {
    out.push(
      `insert into public.badges (slug, name_en, name_id, description, icon) values (${q(b.slug)}, ${q(b.nameEn)}, ${q(b.nameId)}, ${q(b.descriptionEn)}, ${q(b.icon)}) on conflict (slug) do nothing;`,
    );
  }

  // Users (auth + profile)
  const bots = Object.values(db.profiles).filter((p) => p.isDemoBot);
  for (const p of bots) {
    const id = uuid(p.id);
    out.push(
      `insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data) values (${q(id)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(`${p.username}@demo.hopium.family`)}, '', now(), ${q(p.createdAt)}, now(), '{"provider":"email"}', '{}') on conflict (id) do nothing;`,
    );
    out.push(
      `insert into public.profiles (id, username, display_name, bio, country_code, birth_year, interests, holdings_public, share_exact_amounts, tier, kyc_status, language, onboarded_at, risk_accepted_at, created_at) values (${q(id)}, ${q(p.username)}, ${q(p.displayName)}, ${q(p.bio)}, ${q(p.countryCode)}, ${p.birthYear ?? 'null'}, ${arr(p.interests)}, ${p.holdingsPublic}, ${p.shareExactAmounts}, ${q(p.tier)}, 'approved', ${q(p.language)}, ${q(p.onboardedAt)}, ${q(p.riskAcceptedAt)}, ${q(p.createdAt)}) on conflict (id) do update set ${PROFILE_UPSERT};`,
    );
  }
  for (const f of db.follows) {
    out.push(
      `insert into public.follows (follower_id, followee_id, created_at) values (${q(uuid(f.followerId))}, ${q(uuid(f.followeeId))}, ${q(f.createdAt)}) on conflict do nothing;`,
    );
  }
  // Trades: disable fan-out/post trigger (posts are inserted explicitly below).
  out.push('alter table public.trades disable trigger trades_after_insert;');
  for (const t of db.trades) {
    out.push(
      `insert into public.trades (id, user_id, asset_id, symbol, asset_class, side, qty, price, notional, fee, realized_pnl, is_public, copiers, created_at) values (${q(uuid(t.id))}, ${q(uuid(t.userId))}, ${q(t.assetId)}, ${q(t.symbol)}, ${q(t.assetClass)}, ${q(t.side)}, ${t.qty}, ${t.price}, ${t.notional}, ${t.fee}, ${t.realizedPnl}, ${t.isPublic}, ${t.copiers}, ${q(t.createdAt)}) on conflict (id) do nothing;`,
    );
  }
  out.push('alter table public.trades enable trigger trades_after_insert;');
  for (const [key, lots] of Object.entries(db.lots)) {
    const [userId, assetId] = key.split(':') as [string, string];
    const qty = lots.reduce((a, l) => a + Number(l.qty), 0);
    const cost = lots.reduce((a, l) => a + Number(l.qty) * Number(l.price), 0);
    out.push(
      `insert into public.holdings (user_id, asset_id, qty, avg_entry) values (${q(uuid(userId))}, ${q(assetId)}, ${qty.toFixed(12)}, ${(qty > 0 ? cost / qty : 0).toFixed(12)}) on conflict do nothing;`,
    );
  }
  out.push('alter table public.theses disable trigger theses_after_insert;');
  for (const t of db.theses) {
    out.push(
      `insert into public.theses (id, author_id, asset_id, symbol, direction, entry_price, target_price, invalidation_price, timeframe_end, body, status, resolved_at, max_favorable_pct, created_at) values (${q(uuid(t.id))}, ${q(uuid(t.authorId))}, ${q(t.assetId)}, ${q(t.symbol)}, ${q(t.direction)}, ${t.entryPrice}, ${t.targetPrice}, ${t.invalidationPrice}, ${q(t.timeframeEnd)}, ${q(t.body)}, ${q(t.status)}, ${q(t.resolvedAt)}, ${t.maxFavorablePct}, ${q(t.createdAt)}) on conflict (id) do nothing;`,
    );
  }
  out.push('alter table public.theses enable trigger theses_after_insert;');
  out.push(
    'alter table public.likes disable trigger likes_counter;',
    'alter table public.comments disable trigger comments_counter;',
  );
  for (const p of db.posts) {
    out.push(
      `insert into public.posts (id, author_id, kind, trade_id, thesis_id, milestone, like_count, comment_count, created_at) values (${q(uuid(p.id))}, ${q(uuid(p.authorId))}, ${q(p.kind)}, ${p.tradeId ? q(uuid(p.tradeId)) : 'null'}, ${p.thesisId ? q(uuid(p.thesisId)) : 'null'}, ${json(p.milestone)}, ${p.likeCount}, ${p.commentCount}, ${q(p.createdAt)}) on conflict (id) do nothing;`,
    );
  }
  for (const c of db.comments) {
    out.push(
      `insert into public.comments (id, post_id, author_id, body, created_at) values (${q(uuid(c.id))}, ${q(uuid(c.postId))}, ${q(uuid(c.authorId))}, ${q(c.body)}, ${q(c.createdAt)}) on conflict (id) do nothing;`,
    );
  }
  for (const l of db.likes) {
    out.push(
      `insert into public.likes (post_id, user_id) values (${q(uuid(l.postId))}, ${q(uuid(l.userId))}) on conflict do nothing;`,
    );
  }
  out.push(
    'alter table public.likes enable trigger likes_counter;',
    'alter table public.comments enable trigger comments_counter;',
  );
  for (const b of db.userBadges) {
    out.push(
      `insert into public.user_badges (user_id, slug, created_at) values (${q(uuid(b.userId))}, ${q(b.slug)}, ${q(b.awardedAt)}) on conflict do nothing;`,
    );
  }
  // Precomputed all-time leaderboards.
  const pnl = bots
    .map((b) => ({ id: b.id, m: traderMetrics(db.trades.filter((t) => t.userId === b.id)) }))
    .filter((r) => qualifies(r.m));
  for (const { item, rank } of rankBy(pnl, (r) => r.m.pnlPct)) {
    out.push(
      `insert into public.leaderboard_snapshots (period, metric, user_id, rank, value) values ('all_time', 'pnl_pct', ${q(uuid(item.id))}, ${rank}, ${Number(item.m.pnlPct).toFixed(6)});`,
    );
  }
  const acc = bots
    .map((b) => {
      const th = db.theses.filter((t) => t.authorId === b.id && t.status !== 'active');
      return {
        id: b.id,
        v: thesisAccuracyPct(th.filter((t) => t.status === 'hit').length, th.length),
        n: th.length,
      };
    })
    .filter((r) => r.n >= 2);
  for (const { item, rank } of rankBy(acc, (r) => r.v)) {
    out.push(
      `insert into public.leaderboard_snapshots (period, metric, user_id, rank, value) values ('all_time', 'thesis_accuracy', ${q(uuid(item.id))}, ${rank}, ${Number(item.v).toFixed(4)});`,
    );
  }
  const cop = bots.map((b) => ({
    id: b.id,
    v: String(db.trades.filter((t) => t.userId === b.id).reduce((a, t) => a + t.copiers, 0)),
  }));
  for (const { item, rank } of rankBy(cop, (r) => r.v)) {
    out.push(
      `insert into public.leaderboard_snapshots (period, metric, user_id, rank, value) values ('all_time', 'copiers', ${q(uuid(item.id))}, ${rank}, ${item.v});`,
    );
  }
  out.push('commit;', '');
  return out.join('\n');
}

if (require.main === module) {
  const file = resolve(__dirname, '../supabase/seed.sql');
  writeFileSync(file, buildSeedSql());
  console.log(`✓ supabase/seed.sql`);
}
